spring:
  profiles:
    active: dev

  resources:
    static-locations: classpath:/public/,classpath:/statics/

  application:
    name: demo

  datasource:
    url: jdbc:mysql://localhost:3306/chapter4?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    password: root
    username: root
    driver-class-name: com.mysql.jdbc.Driver

# qq邮箱
# JavaMailSender 邮件发送的配置
  mail: 
    host: smtp.qq.com
    username: lqsi6910@qq.com
    password: jfislguslnasbiba
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

# freemarker配置
  freemarker:
      content-type: text/html
      #后缀名
      suffix: .ftl
      template-loader-path: classpath:/templates
      charset: UTF-8
      check-template-location: true

value: myValue

demo:
  mail:
    sender: lqsi6910@qq.com


# 日志配置 
#logging:
#  level:
#    root: info
#    org:
#      springframework: warn
#      mybatis: warn
#  file:
#    max-size: 5M
#    max-history: 30

